[GLOBAL]
pants_version = "2.13.0"

use_deprecated_pex_binary_run_semantics = false
use_deprecated_directory_cli_args_semantics = false

backend_packages.add = [
  "pants.backend.python",
]

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = ["==3.8.14"]
enable_resolves = true

