[anonymous-telemetry]
enabled = false

[GLOBAL]
pants_version = "2.14.0"

backend_packages.add = [
  "pants.backend.python",
]
build_file_prelude_globs = ["pants-plugins/macros.py"]


[source]
root_patterns = ["/"]


[python]
interpreter_constraints = ["==3.8.*"]
enable_resolves = true


[python.resolves]
  duckdb = "3rdparty/python/duckdb.lock"
  http = "3rdparty/python/http.lock"
  default = "3rdparty/python/default.lock"
