[anonymous-telemetry]
enabled = false

[GLOBAL]
pants_version = "2.13.0"

use_deprecated_pex_binary_run_semantics = false
use_deprecated_directory_cli_args_semantics = false

backend_packages.add = [
  "pants.backend.python",
]
build_file_prelude_globs = ["pants-plugins/macros.py"]


[source]
root_patterns = ["/"]


[python]
interpreter_constraints = ["==3.8.14"]
enable_resolves = true


[python.resolves]
  data = "3rdparty/python/data.lock"
  duckdb = "3rdparty/python/duckdb.lock"
  default = "3rdparty/python/default.lock"
